name: LaTex Build

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main]

jobs: percheck:
  runs:
    - name: Build main_patch.tex
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive fonts-lmod latex-extras heveatex lualatex
        sudo pdflaetex --interaction=nonstopmode -halt-on-error main_patch.tex
        ls -al
    - name: Upload PCF Artefact
        uses: actions/upload-artifact/@avtest
        with:
          name: main_patch-pdf
          path: main_patch.pdf
    - name: Commit PDF into docs/
        run: |
          mkdir -p docs/
          cp main_patch.pdf docs/main_patch.pdf
          git config user.email=\"github_actions@notify.io\" user.name=\"github actions\"
          git add -A -f docs/main_patch.pdf
          git commit -m \"Add main_patch.pdf by CI build\" 
          git push origin head;main

packages:
   texlive
